### ISSUE TITLE
Update schema to proper camelCase.

### ISSUE THREAD

**Issue by Seann-Murdock** [microsoft/PackageUploader#20]
We are looking into hosting the schema for package uploader in the schema service where the other api schemas are stored and found a couple of instances of casing that doesn't match schema service guidelines. We should update these and make sure the tool can handle both cases (since we've already released with incorrect casing)

Fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "GetProduct". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/properties/operationName/oneOf/0/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "UploadUwpPackage". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/properties/operationName/oneOf/1/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "UploadXvcPackage". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/properties/operationName/oneOf/2/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "RemovePackages". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/properties/operationName/oneOf/3/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "ImportPackages". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/properties/operationName/oneOf/4/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "PublishPackages". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/properties/operationName/oneOf/5/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "UploadUwpPackage". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/0/if/properties/operationName/oneOf/0/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "UploadXvcPackage". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/0/if/properties/operationName/oneOf/1/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "RemovePackages". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/0/if/properties/operationName/oneOf/2/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "ImportPackages". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/0/if/properties/operationName/oneOf/3/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "PublishPackages". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/0/if/properties/operationName/oneOf/4/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "UploadUwpPackage". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/1/if/properties/operationName/oneOf/0/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "UploadXvcPackage". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/1/if/properties/operationName/oneOf/1/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "UploadXvcPackage". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/2/if/properties/operationName/oneOf/0/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "UploadUwpPackage". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/3/if/properties/operationName/oneOf/0/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "RemovePackages". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/4/if/properties/operationName/oneOf/0/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "PublishPackages". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/5/if/properties/operationName/oneOf/0/const
fail: Microsoft.ProductIngestion.Schema.Validate.Program[1]
Invalid const value "ImportPackages". All const values must be null or contain a non-empty, non-whitespace string, and be camelCase @ https://product-ingestion.azureedge.net/schema/package-uploader-operation-configuration/2021-11-30#/allOf/6/if/properties/operationName/oneOf/0/const

**Comment by alberto-baron** [comment]
done, should be in [this PR](https://github.com/microsoft/PackageUploader/pull/21) if you can review it :)
