### ISSUE TITLE
Package deleting

### ISSUE THREAD

**Issue by baldSun** [microsoft/PackageUploader#36]
Can I delete a package uploaded before by this tool?
I'm working on an auto-upload and publish script. The PackageUploader requires an existing branch, which means if I use the same branch, I have to delete the outdated package manually. This is inconvenient and goes against the purpose of our auto-uploading script.

**Comment by alberto-baron** [comment]
Hi, you should be able to delete packages from the chosen branch by using the tool with the RemovePackages operation before.
You could also create a separate branch used for uploads and then import the packages from that one to the one of your choice, setting up the overwrite setting.

**Comment by lawhelpt** [comment]
https://github.com/microsoft/PackageUploader/blob/main/templates/RemovePackages.json

**Comment by baldSun** [comment]
Thank you so much. I was too focused on the word "delete" to realize that it was actually a "remove" operation. I made it! Thank you again :)
